### ISSUE TITLE
Testing the sample cordova app leads to FastCrop.imodel was not found

### ISSUE THREAD

**Issue by ChrisTomAlx** [abbyysdk/RTR-SDK.Cordova#16]
Hey I have been testing this plugin and I used the sample cordova app in this repo. But I see the error below. Any guidance would be appreciated. Build was successful but when I click start capture button this error is thrown.

**Error description on UI** :-  
`"description": "Capture error: RuntimeException FastCrop.imodel was not found."`

**Android studio logcat** :- 
```java
2020-10-23 16:31:09.807 7436-7436/com.abbyy.rtr.cordova.sample W/System.err: java.lang.RuntimeException: FastCrop.imodel was not found.
2020-10-23 16:31:09.807 7436-7436/com.abbyy.rtr.cordova.sample W/System.err:     at com.abbyy.mobile.rtr.ImageCaptureService.nativeImageCaptureServiceAddImage(Native Method)
2020-10-23 16:31:09.807 7436-7436/com.abbyy.rtr.cordova.sample W/System.err:     at com.abbyy.mobile.rtr.ImageCaptureService$Worker.doWork(ImageCaptureService.java:198)
2020-10-23 16:31:09.807 7436-7436/com.abbyy.rtr.cordova.sample W/System.err:     at com.abbyy.mobile.rtr.CaptureService$Worker.run(CaptureService.java:304)
2020-10-23 16:31:09.807 7436-7436/com.abbyy.rtr.cordova.sample W/System.err:     at java.lang.Thread.run(Thread.java:764)
````

**Comment by ChrisTomAlx** [comment]
whoops the issue was that I did not move the contents of the `assets` folder from the library to the `www/rtr_assets` folder. I only moved the license
